print("hi".upper())
print("lower".lower())
print("Capitalize".capitalize())
print("Swapcase".swapcase())
print("Find".find("d"))
print(len("argument"))
list = ['world']
print(list.append("hello"))
print(list.index("world"))
list.insert(1,"4")
print(list.remove("world"))
list.pop(1)